### ISSUE TITLE
khartes 3d beta crashing

### ISSUE THREAD

**Issue by JamesDarby345** [KhartesViewer/khartes#29]
Keeps crashing with this error, usually when im interacting with something but nothing specific seems to cause it.

Traceback (most recent call last):
  File "/Users/jamesdarby/Documents/VesuviusScroll/GP/khartes/gl_surface_window.py", line 631, in paintGL
    self.paintSlice()
  File "/Users/jamesdarby/Documents/VesuviusScroll/GP/khartes/gl_surface_window.py", line 768, in paintSlice
    larr, self.xyz_arr, zoom_level = self.getBlocks(self.xyz_fbo)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 3, got 2)
[1]    83748 abort      python khartes.py
/Users/jamesdarby/anaconda3/envs/khartes/lib/python3.11/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown                                                 
  warnings.warn('resource_tracker: There appear to be %d '

**Comment by KhartesViewer** [comment]
Thanks for the bug report!
A couple of questions:
1) Are you running on MacOS?
2) Does the program sometimes work?  That is, it sometimes gets to the point where you see data in the map view window?  Or does it always crash before then?

**Comment by KhartesViewer** [comment]
I just pushed a change to the khartes3d-beta branch.  This should fix the crash (printing some diagnostics instead), but I am not sure if it fixes whatever the underlying cause is.  Anyway, please give it a try and let me know how it goes.
Thanks for trying out the beta version!

**Comment by JamesDarby345** [comment]
The changes did fix the issue, works as expected now, which is very well!

**Comment by KhartesViewer** [comment]
Glad to hear it.  Thanks!
